sudo: required
services:
 - docker

before_install:
 - docker build -t yoshi0807/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true yoshi0807/react-test npm test -- --coverage

after_success:
  - docker build -t yoshi0807/multi-client ./client
  - docker build -t yoshi0807/multi-nginx ./nginx
  - docker build -t yoshi0807/multi-server ./server
  - docker build -t yoshi0807/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker hub
  - docker push yoshi0807/multi-client
  - docker push yoshi0807/multi-nginx
  - docker push yoshi0807/multi-server
  - docker push yoshi0807/multi-worker
  